<nav class="navigation_bar">
	<ul class="sticky">
		<li><a href="index.php">Home</a></li>
		<li><a href="product.php">Movies</a></li>
		<li><a href="enquire.php">Booking</a></li>
		<li><a href="enhancements.php">Enhancements</a></li>
		<li><a href="enhancements2.php">Enhancements 2</a></li>
		<li><a href="enhancements3.php">Enhancements 3</a></li>
		<li><a href="login.php">Managers</a></li>
		<li><a href="contact.php">Contact us</a></li>
		<li><a href="about.php">About</a> </li>
		<li><a href="member_register.php">Member register</a> </li>
    </ul>
</nav>